FROM albaike/pstk:latest

USER root
RUN apt install -y git

USER postgres
RUN echo 'export PSTK_ARGS="--extension --schema-path=postllm--1.0.sql /postllm test"' \
    >> ~/.env

WORKDIR /postllm
COPY llama.cpp llama.cpp
USER root
RUN chown -R postgres:postgres /postllm
USER postgres
WORKDIR /postllm/llama.cpp
RUN cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
RUN make
USER root
RUN make install
USER postgres

WORKDIR /postllm
COPY files files
COPY CMakeLists.txt .
COPY postllm.cpp .
COPY postllm.hpp .

RUN cmake .
RUN make

COPY postllm.control .
COPY *.sql .

USER root
RUN make install
RUN echo "shared_preload_libraries = 'postllm'" | tee -a /usr/share/postgresql/postgresql.conf.sample
USER postgres

EXPOSE 5432

CMD ["bash", "/docker_postgres.sh"]