name: Test package release

on:
  push:
    branches:
      - master

jobs:
    test:
      name: test postgres extension
      runs-on: ubuntu-latest
      # Specifying a GitHub environment is optional, but strongly encouraged
      environment: release
      permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
      steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            sudo apt install -y postgresql-common
            sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
            sudo apt install -y postgresql-16 postgresql-client-16
            sudo apt remove -y postgresql-14 postgresql-client-14
            sudo systemctl start postgresql
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
            sudo apt install -y libxslt1-dev libxslt1.1 libxml2 libxml2-dev postgresql-server-dev-16
            python -m pip install --upgrade pip
            pip install pstk

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build extension
          run: make

        - name: Install and test extension
          run: |
            pstk --extension --schema-path=postxml--1.0.sql . test